name: simpler-easier
version: 0.1.0.0

dependencies:
  - base
  - mtl

library:
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs: tests
    dependencies:
    - hspec
    - simpler-easier
